name: jp_index
dependencies:
  - python=3.12
  - pip=24.0
  - pyarrow=17.0.0
  - polars=1.5.0
  - requests=2.32.3
  - fastexcel=0.11.5
  - tqdm=4.66.5
  - sqlmodel==0.0.22
  - pandas==2.2.3
  - requests





