import duckdb


def get_conn(db_path: str) -> duckdb.DuckDBPyConnection:
    return duckdb.connect(db_path)


def init_indicators_table(db_path: str) -> None:
    conn = get_conn(db_path=db_path)


    # Create Indicators table
    conn.sql(
        """
        CREATE TABLE IF NOT EXISTS "indicatorstable" (
            date DATE,
            fiscal INTEGER,
            year INTEGER,
            month INTEGER,
            quarter INTEGER,
            indice_de_actividad_economica FLOAT,
            encuesta_de_grupo_trabajador_ajustada_estacionalmente FLOAT,
            encuesta_de_grupo_trabajador FLOAT,
            encuesta_de_establecimientos_ajustados_estacionalmente FLOAT,
            encuesta_de_establecimientos FLOAT,
            indicadores_de_turismo FLOAT,
            indicadores_de_construccion FLOAT,
            indicadores_de_ingresos_netos FLOAT,
            indicadores_de_energia_electrica FLOAT,
            indicadores_de_comercio_exterior FLOAT,
            indicadores_de_quiebras FLOAT,
            indicadores_de_ventas_al_detalle_a_precios_corrientes FLOAT,
            precios_promedios_mensuales_de_gasolina_al_detal_en_puerto_rico FLOAT,
            indice_de_precios_al_consumidor_2006_100 FLOAT,
            indicadores_de_transportacion FLOAT,
            indices_coincidentes_de_actividad_economica FLOAT,
            encuesta_de_establecimientos_manufactura FLOAT
        );
        """
    )


def init_consumer_table(db_path: str) -> None:
    conn = get_conn(db_path=db_path)

    # Create Consumer table
    conn.sql(
        """
        CREATE TABLE IF NOT EXISTS "consumertable" (
            date DATETIME,
            year INTEGER,
            month INTEGER,
            quarter INTEGER,
            fiscal INTEGER,
            ropa FLOAT,
            ropa_de_hombres FLOAT,
            ropa_de_ninos FLOAT,
            ropa_de_mujer FLOAT,
            ropa_de_ninas FLOAT,
            calzado FLOAT,
            ropa_de_bebe_y_de_infantes FLOAT,
            relojes_y_joyeria FLOAT,
            educacion_y_comunicacion FLOAT,
            materiales_educativos FLOAT,
            matricula_mensualidades_y_cuido_de_ninos FLOAT,
            correo_y_otros_servicios_postales FLOAT,
            telefonos FLOAT,
            otros_servicios_informativos FLOAT,
            alimentos_y_bebidas FLOAT,
            cereales_y_productos_de_cereales FLOAT,
            productos_horneados FLOAT,
            carne_de_res FLOAT,
            carne_de_cerdo FLOAT,
            otras_carnes FLOAT,
            carne_de_aves FLOAT,
            pescados_y_mariscos FLOAT,
            huevos FLOAT,
            productos_lacteos_y_relacionados FLOAT,
            frutas_frescas FLOAT,
            vegetales_frescos FLOAT,
            frutas_y_vegetales_elaborados FLOAT,
            jugos_de_frutas_y_vegetales_y_bebidas_sin_alcohol FLOAT,
            material_para_bebidas_incluyendo_cafe_y_te FLOAT,
            azucares_y_endulzadores FLOAT,
            grasas_aceites_y_aderezos FLOAT,
            otros_alimentos FLOAT,
            alimentos_para_consumo_fuera_del_hogar FLOAT,
            bebidas_alcoholicas_para_consumo_en_el_hogar FLOAT,
            bebidas_alcoholicas_para_consumo_fuera_del_hogar FLOAT,
            otros_articulos_y_servicios FLOAT,
            tabaco_y_productos_relacionados FLOAT,
            productos_para_el_cuidado_personal FLOAT,
            servicios_cuidado_personal FLOAT,
            servicios_personales_miscelaneos FLOAT,
            otros_gastos FLOAT,
            alojamiento FLOAT,
            alquiler_de_la_residencia_primaria FLOAT,
            alojamiento_fuera_del_hogar FLOAT,
            alquiler_equivalente_de_la_vivienda_poseida FLOAT,
            seguros_de_la_vivienda_o_de_inquilinos FLOAT,
            combustible_para_la_vivienda FLOAT,
            electricidad FLOAT,
            agua_alcantarillados_y_limpieza_de_pozos_septicos FLOAT,
            cortinas_alfombras_y_otros_similares FLOAT,
            mobiliario FLOAT,
            enseres_del_hogar FLOAT,
            otros_equipos_del_hogar FLOAT,
            herramientas_equipo_para_uso_exterior_y_articulos_de_ferreteria FLOAT,
            articulos_del_hogar FLOAT,
            servicios_para_el_hogar FLOAT,
            cuidado_medico FLOAT,
            medicinas_recetadas_y_vacunas FLOAT,
            medicinas_no_recetadas_y_equipo_medico FLOAT,
            servicios_profesionales FLOAT,
            hospitales_y_servicios_relacionados FLOAT,
            seguros_de_salud FLOAT,
            entretenimiento FLOAT,
            video_y_audio FLOAT,
            mascotas_productos_y_servicios_para_mascotas FLOAT,
            productos_deportivos FLOAT,
            fotografia FLOAT,
            otros_productos_para_entretenimiento FLOAT,
            servicios_para_el_entretenimiento FLOAT,
            libros_y_revistas FLOAT,
            transporte FLOAT,
            vehiculos_compra_y_alquiler FLOAT,
            combustible_para_motores_y_otros FLOAT,
            piezas_y_equipos_para_vehiculos_de_motor FLOAT,
            mantenimiento_y_reparacion_de_vehiculos FLOAT,
            seguros_para_vehiculos_de_motor FLOAT,
            tarifas_para_vehiculos_de_motor FLOAT,
            transporte_publico FLOAT,
            todos_los_articulos_y_servicios FLOAT
        );
        """
    )

def init_activity_table(db_path: str) -> None:
    conn = get_conn(db_path=db_path)

    # Create Indicators table
    conn.sql(
        """
        CREATE TABLE IF NOT EXISTS "activitytable" (
            date DATETIME,
            index FLOAT
        );
        """
    )

def init_awards_table(db_path: str) -> None:
    conn = get_conn(db_path=db_path)

    conn.sql(
        """
        CREATE TABLE IF NOT EXISTS AwardTable (
            assistance_transaction_unique_key TEXT,
            assistance_award_unique_key TEXT,
            award_id_fain TEXT,
            modification_number TEXT,
            award_id_uri TEXT,
            sai_number TEXT,
            federal_action_obligation FLOAT,
            total_obligated_amount FLOAT,
            total_outlayed_amount_for_overall_award FLOAT,
            indirect_cost_federal_share_amount FLOAT,
            non_federal_funding_amount FLOAT,
            total_non_federal_funding_amount FLOAT,
            face_value_of_loan FLOAT,
            original_loan_subsidy_cost FLOAT,
            total_face_value_of_loan FLOAT,
            total_loan_subsidy_cost FLOAT,
            generated_pragmatic_obligations FLOAT,
            disaster_emergency_fund_codes_for_overall_award TEXT,
            outlayed_amount_from_COVID_19_supplementals_for_overall_award FLOAT,
            obligated_amount_from_COVID_19_supplementals_for_overall_award FLOAT,
            outlayed_amount_from_IIJA_supplemental_for_overall_award FLOAT,
            obligated_amount_from_IIJA_supplemental_for_overall_award FLOAT,
            action_date TEXT,
            action_date_fiscal_year INTEGER,
            period_of_performance_start_date TEXT,
            period_of_performance_current_end_date TEXT,
            awarding_agency_code TEXT,
            awarding_agency_name TEXT,
            awarding_sub_agency_code TEXT,
            awarding_sub_agency_name TEXT,
            awarding_office_code TEXT,
            awarding_office_name TEXT,
            funding_agency_code TEXT,
            funding_agency_name TEXT,
            funding_sub_agency_code TEXT,
            funding_sub_agency_name TEXT,
            funding_office_code TEXT,
            funding_office_name TEXT,
            treasury_accounts_funding_this_award TEXT,
            federal_accounts_funding_this_award TEXT,
            object_classes_funding_this_award TEXT,
            program_activities_funding_this_award TEXT,
            recipient_uei TEXT,
            recipient_duns TEXT,
            recipient_name TEXT,
            recipient_name_raw TEXT,
            recipient_parent_uei TEXT,
            recipient_parent_duns TEXT,
            recipient_parent_name TEXT,
            recipient_parent_name_raw TEXT,
            recipient_country_code TEXT,
            recipient_country_name TEXT,
            recipient_address_line_1 TEXT,
            recipient_address_line_2 TEXT,
            recipient_city_code TEXT,
            recipient_city_name TEXT,
            prime_award_transaction_recipient_county_fips_code TEXT,
            recipient_county_name TEXT,
            prime_award_transaction_recipient_state_fips_code TEXT,
            recipient_state_code TEXT,
            recipient_state_name TEXT,
            recipient_zip_code TEXT,
            recipient_zip_last_4_code TEXT,
            prime_award_transaction_recipient_cd_original TEXT,
            prime_award_transaction_recipient_cd_current TEXT,
            recipient_foreign_city_name TEXT,
            recipient_foreign_province_name TEXT,
            recipient_foreign_postal_code TEXT,
            primary_place_of_performance_scope TEXT,
            primary_place_of_performance_country_code TEXT,
            primary_place_of_performance_country_name TEXT,
            primary_place_of_performance_code TEXT,
            primary_place_of_performance_city_name TEXT,
            prime_award_transaction_place_of_performance_county_fips_code TEXT,
            primary_place_of_performance_county_name TEXT,
            prime_award_transaction_place_of_performance_state_fips_code TEXT,
            primary_place_of_performance_state_name TEXT,
            primary_place_of_performance_zip_4 TEXT,
            prime_award_transaction_place_of_performance_cd_original TEXT,
            prime_award_transaction_place_of_performance_cd_current TEXT,
            primary_place_of_performance_foreign_location TEXT,
            cfda_number TEXT,
            cfda_title TEXT,
            funding_opportunity_number TEXT,
            funding_opportunity_goals_text TEXT,
            assistance_type_code TEXT,
            assistance_type_description TEXT,
            transaction_description TEXT,
            prime_award_base_transaction_description TEXT,
            business_funds_indicator_code TEXT,
            business_funds_indicator_description TEXT,
            business_types_code TEXT,
            business_types_description TEXT,
            correction_delete_indicator_code TEXT,
            correction_delete_indicator_description TEXT,
            action_type_code TEXT,
            action_type_description TEXT,
            record_type_code TEXT,
            record_type_description TEXT,
            highly_compensated_officer_1_name TEXT,
            highly_compensated_officer_1_amount FLOAT,
            highly_compensated_officer_2_name TEXT,
            highly_compensated_officer_2_amount FLOAT,
            highly_compensated_officer_3_name TEXT,
            highly_compensated_officer_3_amount FLOAT,
            highly_compensated_officer_4_name TEXT,
            highly_compensated_officer_4_amount FLOAT,
            highly_compensated_officer_5_name TEXT,
            highly_compensated_officer_5_amount FLOAT,
            usaspending_permalink TEXT,
            initial_report_date TEXT,
            last_modified_date TEXT,
            fiscal_year INTEGER
        )
        """
    )

def init_energy_table(db_path: str) -> None:
    conn = get_conn(db_path=db_path)

    conn.sql(
        """
    CREATE TABLE IF NOT EXISTS EnergyTable (
            mes TEXT,
            generacion_bruta_mkwh FLOAT,
            generacion_neta_mkwh FLOAT,
            demanda_maxima_mw FLOAT,
            generacion_bruta_total_aee_mkwh FLOAT,
            generacion_bruta_con_petroleo_mkwh FLOAT,
            generacion_bruta_con_hidroelectrica_mkwh FLOAT,
            generacion_bruta_con_gas_natural_mkwh FLOAT,
            generacion_netatotal_aee_mkwh FLOAT,
            generacion_neta_con_petroleo_mkwh FLOAT,
            generacion_neta_con_hidroelectrica_mkwh FLOAT,
            generacion_neta_con_gas_natural_mkwh FLOAT,
            generacion_total_con_energia_comprada_mkwh FLOAT,
            generacion_con_energia_comprada_gas_natural_mkwh FLOAT,
            generacion_con_energia_comprada_carbon_mkwh FLOAT,
            generacion_con_energia_comprada_fotovoltaica_mkwh FLOAT,
            generacion_con_energia_comprada_eolica_mkwh FLOAT,
            generacion_con_energia_comprada_otros_varias_tecnologias1_mkwh FLOAT,
            costo_por_kwh_comprado_cent_kwh2 FLOAT,
            consumo_residencial_mkwh FLOAT,
            consumo_comercial_mkwh FLOAT,
            consumo_industrial_mkwh FLOAT,
            consumo_alumbrado_publico_mkwh FLOAT,
            consumo_agricola_mkwh FLOAT,
            consumo_otros_mkwh FLOAT,
            consumo_total_mkwh FLOAT,
            clientes_activos_clase_residencial FLOAT,
            clientes_activos_clase_comercial FLOAT,
            clientes_activos_clase_industrial3 FLOAT,
            clientes_activos_clase_alumbrado_publico FLOAT,
            clientes_activos_clase_agricola FLOAT,
            clientes_activos_clase_otros FLOAT,
            clientes_activos_todas_las_clases FLOAT,
            ingreso_basico_clase_residencial_mdollar FLOAT,
            ingreso_basico_clase_comercial_mdollar FLOAT,
            ingreso_basico_clase_industrial_mdollar FLOAT,
            ingreso_basico_clase_alumbrado_publico_mdollar FLOAT,
            ingreso_basico_clase_agricola_mdollar FLOAT,
            ingreso_basico_clase_otros_mdollar FLOAT,
            total_ingreso_basico_todas_las_clases_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_residencial_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_comercial_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_industrial_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_alumbrado_publico_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_agricola_mdollar FLOAT,
            ingreso_tarifa_provisional_clase_otros_mdollar FLOAT,
            total_ingreso_tarifa_provisional_todas_las_clases_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_residencial_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_comercial_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_industrial_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_agricola_mdollar FLOAT,
            ingresos_ajuste_combustible_clase_otros_mdollar FLOAT,
            total_ingresos_ajuste_combustible_todas_las_clases_mdollar FLOAT,
            ingresos_energia_comprada_clase_residencial_mdollar FLOAT,
            ingresos_energia_comprada_clase_comercial_mdollar FLOAT,
            ingresos_energia_comprada_clase_industrial_mdollar FLOAT,
            ingresos_energia_comprada_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_energia_comprada_clase_agricola_mdollar FLOAT,
            ingresos_energia_comprada_clase_otros_mdollar FLOAT,
            total_energia_comprada_todas_las_clases_mdollar FLOAT,
            ingresos_celi_clase_residencial_mdollar FLOAT,
            ingresos_celi_clase_comercial_mdollar FLOAT,
            ingresos_celi_clase_industrial_mdollar FLOAT,
            ingresos_celi_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_celi_clase_agricola_mdollar FLOAT,
            ingresos_celi_clase_otros_mdollar FLOAT,
            total_ingresos_celi_todas_las_clases_mdollar FLOAT,
            ingresos_subsidio_hh_clase_residencial_mdollar FLOAT,
            ingresos_subsidio_hh_clase_comercial_mdollar FLOAT,
            ingresos_subsidio_hh_clase_industrial_mdollar FLOAT,
            ingresos_subsidio_hh_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_subsidio_hh_clase_agricola_mdollar FLOAT,
            ingresos_subsidio_hh_clase_otros_mdollar FLOAT,
            total_ingresos_subsidio_hh_todas_las_clases_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_residencial_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_comercial_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_industrial_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_agricola_mdollar FLOAT,
            ingresos_subsidio_nhh_clase_otros_mdollar FLOAT,
            total_ingresos_subsidio_nhh_todas_las_clases_mdollar FLOAT,
            ingresos_ee_clase_residencial_mdollar FLOAT,
            ingresos_ee_clase_comercial_mdollar FLOAT,
            ingresos_ee_clase_industrial_mdollar FLOAT,
            ingresos_ee_clase_alumbrado_publico_mdollar FLOAT,
            ingresos_ee_clase_agricola_mdollar FLOAT,
            ingresos_ee_clase_otros_mdollar FLOAT,
            total_ingresos_ee_todas_las_clases_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_residencial_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_comercial_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_industrial_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_alumbrado_publico_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_agricola_mdollar FLOAT,
            devolucion_tarifa_provisional_tup_clase_otros_mdollar FLOAT,
            total_devolucion_tarifa_provisional_tup_todas_las_clases_mdollar FLOAT,
            ingreso_total_clase_residencial_mdollar FLOAT,
            ingreso_total_clase_comercial_mdollar FLOAT,
            ingreso_total_clase_industrial_mdollar FLOAT,
            ingreso_total_clase_alumbrado_publico_mdollar FLOAT,
            ingreso_total_clase_agricola_mdollar FLOAT,
            ingreso_total_clase_otros_mdollar FLOAT,
            ingreso_total_todas_las_clases_mdollar FLOAT,
            costo_promedio_ingreso_basico_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_basico_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_basico_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_basico_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_basico_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_basico_clase_otros_centkwh FLOAT,
            costo_promedio_ingreso_basico_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_combustible_clase_otros_centkwh FLOAT,
            costo_promedio_ingreso_combustible_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_industrial_cent FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_clase_otros_centkwh FLOAT,
            costo_promedio_ingreso_energia_comprada_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_celi_clase_otros_centkwh FLOAT,
            total_costo_promedio_ingreso_celi_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_hh_clase_otros_centkwh FLOAT,
            total_costo_promedio_ingreso_subsidio_hh_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_subsidio_nhh_clase_otros_centkwh FLOAT,
            total_costo_promedio_ingreso_subsidio_nhh_todas_las_clases_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_residencial_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_comercial_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_industrial_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_alumbrado_publico_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_agricola_centkwh FLOAT,
            costo_promedio_ingreso_ee_clase_otros_centkwh FLOAT,
            total_costo_promedio_ingreso_ee_todas_las_clases_centkwh FLOAT,
            costo_promedio_centkwh_clase_residencial FLOAT,
            costo_promedio_centkwh_clase_comercial FLOAT,
            costo_promedio_centkwh_clase_industrial FLOAT,
            costo_promedio_centkwh_clase_alumbrado_publico FLOAT,
            costo_promedio_centkwh_clase_agricola FLOAT,
            costo_promedio_centkwh_clase_otros FLOAT,
            costo_promedio_centkwh_todas_las_clases FLOAT,
            dollarbbl_quemados_residual FLOAT,
            dollarbbl_quemados_destilado FLOAT,
            dollarbbl_quemados_gas_natural FLOAT,
            total_dollarbbl_quemados FLOAT,
        )
        """
    )